spring:
  application:
    name: devtanush-spring-cloud-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: stock-enquiry
          uri: http://localhost:8700/
          predicates:
            - Path=/product-enquiry/**

server:
  port: ${port:8900}
